window.allCards = [];

// ==========================================
// ELÄINTEN GRAFIIKAT JA 150+ KIROILEVAA SOLVAUSTA
// ==========================================
const doodleSVGs = [
    // 1. Kiroileva Siili (Piikikäs selkä, pieni kuono)
    "M 30 70 Q 20 70 20 60 Q 30 20 60 20 Q 80 20 80 50 Q 80 70 70 70 Z M 25 50 L 15 40 M 35 35 L 25 20 M 50 25 L 50 10 M 65 30 L 75 15 M 75 45 L 90 40 M 30 60 L 35 60", 
    // 2. Vihainen Kissa (Terävät korvat, viikset, vihaiset silmät)
    "M 30 70 L 30 40 L 20 20 L 40 30 L 60 30 L 80 20 L 70 40 L 70 70 Z M 20 50 L 10 45 M 20 55 L 10 55 M 80 50 L 90 45 M 80 55 L 90 55 M 40 45 L 45 45 M 60 45 L 55 45",
    // 3. Äkäinen Karhu (Pyöreät korvat, leveä pää)
    "M 25 70 C 10 70 10 30 35 30 C 35 20 45 20 50 30 C 55 20 65 20 65 30 C 90 30 90 70 75 70 Z M 40 45 L 45 45 M 60 45 L 55 45 M 50 55 C 45 60 55 60 50 55",
    // 4. Vittuuntunut Lintu (Nokka, siivet)
    "M 50 70 C 20 70 30 40 50 30 C 70 40 80 70 50 70 M 50 30 L 45 20 L 50 25 L 55 20 Z M 20 50 L 30 45 M 80 50 L 70 45 M 40 40 L 45 40 M 60 40 L 55 40 M 50 50 L 45 60 L 55 60 Z",
    // 5. Kyllästynyt Koira (Luppakorvat, iso kuono)
    "M 35 70 C 20 70 30 30 50 30 C 70 30 80 70 65 70 Z M 35 30 C 25 30 20 50 25 60 M 65 30 C 75 30 80 50 75 60 M 40 45 L 45 45 M 60 45 L 55 45 M 50 60 C 45 65 55 65 50 60",
    // 6. Tuhma Porsas (Kärsä, saparohäntä)
    "M 30 65 C 20 65 20 35 50 35 C 80 35 80 65 70 65 Z M 40 50 C 40 45 60 45 60 50 C 60 55 40 55 40 50 M 45 50 L 47 50 M 55 50 L 53 50 M 80 45 C 85 40 90 50 85 55 M 35 35 L 30 25 L 40 35 M 65 35 L 70 25 L 60 35"
];

const insults = [
    "V*ttu mikä heitto, ootko sä koskaan edes pitänyt kiekkoa kädessä?",
    "P*rkele, mummonikin puttaa paremmin, ja se on ollut kuolleena 10 vuotta.",
    "S**tanan sirkkeli, puut tykkää susta enemmän ku sun omat vanhemmat.",
    "Ei h*lvetti, jopa Jeesus itkee ton sun tekniikan takia.",
    "P*ska veto. Sun draivi on lyhyempi ku mun kärsivällisyys.",
    "V*tun hieno lay-up! Ai se olikin sun maksimidraivi?",
    "Mene s**tana takas rangelle, tää on noloa meille kaikille.",
    "P*rkeleen rystykääntö, kiekko lensi enemmän taakse ku eteen.",
    "Miten sä v*ttu onnistut missaamaan 2 metristä?",
    "H*lvetin hieno puuosuma! Tähtäsitkö sä siihen vai ootko vaan p*ska?",
    "V*tun noloa. Caddiekin lähti äsken kotiin häpeästä.",
    "S**tanan kalliit kiekot, mut taidot on 0 euroa.",
    "P*rkele, sun rystyheitto näyttää siltä ku yrittäisit heittää pesukonetta.",
    "V*tun grippilokki! Ota se käsi irti siitä muovista ajoissa.",
    "P*ska putti, p*ska mies. Yksinkertaista.",
    "H*lvetti soikoon, sun kiekko etsii enemmän sieniä ku metsästäjät.",
    "V*ttu sulaa aivot ku joutuu kattoon tota sun räpellystä.",
    "S**tana mikä uikku, ootko harkinnu vaikka pitsinnypläystä?",
    "P*rkeleen amatööri, sun bägi painaa enemmän ku sun ÄO.",
    "V*tun hieno rolleri! Harmi vaan että se pysähty ekaan käpyyn.",
    "P*ska heitto! Edes myötätuuli ei halua auttaa sua.",
    "H*lvetin puunhakkaaja. Montako kuutiota teit polttopuuta tolla draivilla?",
    "V*ttu sä olet hidas! Heitä nyt s**tana!",
    "P*rkele, heitä silmät kii ens kerralla, ei se ainakaan huonommin voi mennä.",
    "V*tun kiva kattoa ku yrität. Et siis onnistu, mut yrität.",
    "S**tanan vässykkä, ota se putteri ja laita se sisään!",
    "P*ska formi! Sun x-step näyttää humalaisen ripaskalta.",
    "H*lvetti, mä voisin heittää vasemmalla kädellä paremmin ku sä.",
    "V*ttu mikä antsa, se käänsi suoraan naapurin takapihalle.",
    "P*rkeleen luuseri, älä syytä tuulta, syytä peiliä.",
    "S**tana, edes ammattilainen ei keksis tekosyytä tolle heitolle.",
    "V*tun hienot vaatteet, harmi ettei ne korjaa sun tekniikkaa.",
    "P*ska laji sulle. Oikeesti, lopeta ajoissa.",
    "H*lvetin tunari, sun kiekko lens melkein 10 metriä!",
    "V*ttu säästetään kaikkien aikaa ja merkkaa suoraan tuplabogey.",
    "P*rkeleen noloa. En halua edes seisoa sun lähellä tiillä.",
    "S**tana sun upsit tulee aina suoraan omaan päähän.",
    "V*tun turisti, lopeta se ranteella vemputtaminen.",
    "P*skat taidot. Ostit sitte Paul McBethin kiekon luullen et se auttaa?",
    "H*lvetti sä oot surkee. Voisitko mennä pelaan pallo-golfia?",
    "V*ttu sä heität kovaa! Harmi ettei se osu ikinä väylälle.",
    "P*rkeleen sokea kana, kori on tuolla päin!",
    "S**tanan räpyläkäsi, ote lipsuu pahemmin ku Suomen talous.",
    "V*tun väsyny suoritus. Ootko ollu ryyppäämässä vai ootko aina tollanen?",
    "P*ska heitto! Anna ku mä näytän miten tää laji toimii.",
    "H*lvetin puolisokea, etkö nää missä se kori oikein on?",
    "V*ttu sä oot huono! Miten ees fysiikka sallii tommosen heiton?",
    "P*rkele sun kämmen näyttää siltä ku oisit heittämässä kiveä mereen.",
    "S**tanan säälittävä yritys. Käy hakeen kiekkos ja häpee.",
    "V*tun itkijä, lopeta se valittaminen ja opettele heittään.",
    "P*ska putti! Laita se markkeri perseesees jos et muuta osaa.",
    "H*lvetti sentään, pitäiskö mun soittaa sulle opaskoira?",
    "V*ttu mikä hysse! Se meni niin korkeelle et lintu sai sydärin.",
    "P*rkeleen ränniheittäjä, ootko koskaan osunu ykkösväliin?",
    "S**tanan alarauta, aina sä kolistelet noita peltejä.",
    "V*tun hyvä lay-up 2 metristä. Ootko ylpeä?",
    "P*ska draivi, p*skemmat housut. Mee kotiin.",
    "H*lvetin surkimus, jopa mä häpeän sun puolesta.",
    "V*ttu sä et osaa! Lopeta se muovin paiskonta.",
    "P*rkele onks sulla kädessä joku asennusvirhe?",
    "S**tanan tyhmä veto. Miks helvetissä valitsit ton linjan?",
    "V*tun puusilmä, se kiekko löytyy varmaan toiselta mantereelta.",
    "P*skamainen keli, p*ska heittäjä. Täydellinen kombo.",
    "H*lvetti sä roiskit tota kiekkoa ku hullu koira.",
    "V*ttu sä oot naurettava. C1-putit ohi vasemmalta ja oikeelta.",
    "P*rkeleen sirkuspelle, heitä välillä normaalisti!",
    "S**tanan metkuttaja, koita edes pysyä pois OB:lta kerran.",
    "V*tun räkänen heitto, ei edes pyörinyt.",
    "P*ska peli, mut hei, oothan sä aina ollut tollanen.",
    "H*lvetin tunari, sun kiekko pelkää sua. Siks se karkaa puskaan.",
    "V*ttu mua itkettää sun puolesta.",
    "P*rkele miten sä voit olla noin p*ska joka kerta?",
    "S**tanan alisuorittaja, sä oot tän lajin häpeäpilkku.",
    "V*tun kädetön apina, ote irti kiekosta ajoissa!",
    "P*ska suoritus. Oisit ees jättäny draiverit kotiin.",
    "H*lvetin hyvä yritys. Ei ollu lähelläkään.",
    "V*ttu sun saatto on niin lyhyt et näyttää ku saisit sähköiskun.",
    "P*rkele mee plokkaan marjoja tonne metsään, kun kerran siellä oot.",
    "S**tanan harrastelija, kato YouTubesta vähän mallia.",
    "V*tun läpsyttelijä, heitä sitä kiekkoa äläkä silitä sitä.",
    "P*ska formi! Näyttää ku sorsalla ois ripuli.",
    "H*lvetti mä en kestä enää kattoo tota.",
    "V*ttu sun fore näyttää siltä et sulta lähtee käsi irti.",
    "P*rkele mikä roikku, ootko heittämässä vappupalloa?",
    "S**tanan narukäsi, eikö irtoa enempää tehoa?",
    "V*tun noloo. Sä oot syy miks lajia ei arvosteta.",
    "P*ska linja. Miten sä edes keksit heittää tosta?",
    "H*lvetin metsäpeikko, taasko sä olet siellä tiheikössä?",
    "V*ttu oot varmaan ylpeä tosta heitosta, vaikka se meni päin v*ttua.",
    "P*rkeleen sunnuntaipelaaja, sun peli on yhtä kärsimystä.",
    "S**tana ootko sä sokea vai vaan äärimmäisen tyhmä?",
    "V*tun hyvä! Eikun siis s**tanan p*ska.",
    "P*skaa! Silkkaa p*skaa koko sun kierros.",
    "H*lvetti sentään, en tiennyt et ihminen voi olla noin koordinaatiokyvytön.",
    "V*ttu sä oot pehmeä. Anna vähän runtua siihen heittoon!",
    "P*rkele sun tekniikalla ei pitäis antaa poistua kotoa.",
    "S**tanan epäonnistuja, laita kiekot myyntiin Toriin heti.",
    "V*tun hyvä pomppu! Harmi et se pomppas suoraan OB:lle.",
    "P*ska peli. Jos oisit koira, sut vietäis piikille tosta suorituksesta.",
    "H*lvetin vässykkä, puttaa se sisään äläkä pelkää!",
    "V*ttu sääli on sairautta, mut mä oikeesti säälin sua just nyt.",
    "P*rkele sä olet toivoton tapaus.",
    "S**tana laita se PDGA-numero piiloon tolla pelillä.",
    "V*tun lapanen, mihin sä sen oikein heitit?",
    "P*ska mies, p*skempi fore.",
    "H*lvetti mikä laiskanlinna, eikö yhtään kiinnosta yrittää?",
    "V*ttu mun aivot sulaa sun heittojen takia.",
    "P*rkeleen pullasorsa, lopeta se leipominen ja heitä!",
    "S**tanan säheltäjä, kiekko ei oo mikään frisbee-lelu rannalla.",
    "V*tun hieno tuplabogey! Sä oot tän radan kingi.",
    "P*ska veto! Pitäiskö sun kokeilla jotain helpompaa, niiku nukkumista?",
    "H*lvetti sä näytät ihan v*tun naurettavalta tiillä.",
    "V*ttu sä et osaa ees teipata sormia oikein.",
    "P*rkele mä häpeän olla samassa poolissa sun kanssa.",
    "S**tanan vinkuja, turpa kii ja heitä paremmin.",
    "V*tun idiootti, kiekossa on liidosta kyse, ei kaivamisesta.",
    "P*ska kiekko vai p*ska heittäjä? Mä tiedän vastauksen.",
    "H*lvetin raivostuttavaa kattoa sun putteja.",
    "V*ttu sun grip-lock on legendaarinen, päin v*ttua joka kerta.",
    "P*rkele sun svingi on niiku ruosteinen portti.",
    "S**tanan pösilö, taasko kiekko meni veteen?",
    "V*tun itkupilli, eihän se oo ku muovia metsässä.",
    "P*ska peli, ootko aatellu et frisbeegolf ei vaan oo sua varten?",
    "H*lvetti mä heittäisin sut perässä sinne järveen.",
    "V*ttu sä oot sysip*ska. Ei voi muuta sanoa.",
    "P*rkeleen velttoilija, missä sun asenne on?",
    "S**tana sun avaukset on lyhyempiä ku mun putit.",
    "V*tun munapää, älä ota tuurista kunniaa itelles.",
    "P*skan marjat, et sä tota yrittänyt hakea.",
    "H*lvetin aivokuollut linjavalinta.",
    "V*ttu sä teet mut fyysisesti sairaaks tolla formilla.",
    "P*rkele laita silmät auki kun heität!",
    "S**tanan sähläri, ei tää oo rakettitiedettä.",
    "V*tun p*ska. Anna kiekot mulle ja painu v*ttuun täältä.",
    "P*ska sää, p*ska rata, mut sä oot p*skin kaikista.",
    "H*lvetti ootko sä liimannu sen kiekon kiinni käteens?",
    "V*ttu mikä nyssykkä. Edes vauva ei heitä noin hiljaa.",
    "P*rkeleen surkimus, toi oli säälittävin heitto mitä oon ikinä nähny.",
    "S**tanan noloa. Älä kerro kellekään et tunnet mut.",
    "V*tun idiootti, luitko sä tuulen ihan tarkotuksella väärin?",
    "P*ska peli. Jos tyhmyydestä sais miinuksia, oisit radan ennätysmies.",
    "H*lvetti sä tuhoat mun elämänhalun tolla pelillä.",
    "V*ttu ota ittees niskasta kii ja lopeta toi s**tanan sähläys!",
    "P*rkele sä olet friban musta aukko, imeet kaiken ilon lajista.",
    "S**tana mun isoäiti on rollaattorissa ja voittais sut yhdellä kädellä.",
    "V*tun p*ska, sun draivi muistuttaa mua oksennuksesta: molemmat tulee yllättäen ja menee päin h*lvettiä.",
    "P*ska putti. Ja p*skat on sun housuissakin.",
    "H*lvetti sun rysty on v*tun surullinen näky."
];

// ==========================================
// TASO 1: PIENET SABOTAASIT (Halpoja pelata, pientä kiusaa, Max 2 per väylä)
// ==========================================
const minorBases = [
    { n: "Silmät kiinni", d: "Kohde joutuu laittamaan silmät kiinni juuri ennen heiton irrotusta." },
    { n: "Kurki-Asento", d: "Heiton aikana toinen jalka ei saa koskea maahan." },
    { n: "Sammakko", d: "Mene syvään kyykkyyn ja suorita heitto siitä asennosta." },
    { n: "Pyörähdys", d: "Pyörähdä 360 astetta vauhdissa ja heitä heti perään." },
    { n: "Vauhtijarru", d: "Pysähdy kokonaan 1 sekunniksi tukijalalle juuri ennen vetoa." },
    { n: "Häirintä", d: "Saat seisoa 2 metrin päässä kohteesta ja pitää meteliä heiton aikana." },
    { n: "Paikaltaveto", d: "Seuraavassa heitössä et saa ottaa yhtään vauhtiaskelta." },
    { n: "Matala asento", d: "Heitä siten, että hartiasi ovat maksimissaan metrin korkeudella maasta." },
    { n: "Selin koriin", d: "Heitto on irrotettava täysin selkä koria kohden." },
    { n: "Kävelyvauhti", d: "Vauhtia saa ottaa, mutta vain hitaasti kävellen (ei juoksua)." },
    { n: "Pakkohymy", d: "Kohteen on hymyiltävä leveästi ja hampaat irvessä koko suorituksen ajan." },
    { n: "Pikaveto", d: "Kohteella on tasan 5 sekuntia aikaa heittää siitä, kun hän saapuu kiekolleen." },
    { n: "Laukku selässä", d: "Bägi on pidettävä selässä koko heittosuorituksen ajan." },
    { n: "Polviltaan", d: "Seuraava heitto on suoritettava vähintään toinen polvi maassa." },
    { n: "Erikoisgrippi", d: "Heitä seuraava heitto niin, että peukalosi on kiekon pohjapuolella." },
    { n: "Tuijotus", d: "Saat mennä seisomaan aivan kohteen näkökenttään ja tuijottaa häntä silmiin." },
    { n: "Ei saattoa", d: "Käden on pysähdyttävä kuin seinään heti, kun kiekko irtoaa sormista." },
    { n: "Keskisormi", d: "Keskisormen on oltava täysin suorana irti kiekosta koko heiton ajan." },
    { n: "Tasajalkaloikka", d: "Ota vauhtia vain tasajalkaloikilla." },
    { n: "Hyppyputti", d: "Seuraava heitto (vaikka alle 10m) on pakko suorittaa hyppyputtina." },
    { n: "Kuiskailu", d: "Kohde saa puhua vain kuiskaten koko loppuväylän ajan." },
    { n: "Tuulen haistelu", d: "Kohteen on nostettava sormi pystyyn ja 'haisteltava tuulta' 10 sekuntia ennen heittoa." },
    { n: "Pääkallistus", d: "Pää on pidettävä kallistettuna täysin oikealle olkapäälle koko suorituksen ajan." },
    { n: "Kädet ristiin", d: "Ota kiekosta kiinni siten, että kätesi ovat ristissä ennen vetoa." },
    { n: "Lauluhetki", d: "Kohteen on laulettava ääneen jokin lastenlaulu heittonsa aikana." },
    { n: "Varoitus", d: "Huuda 'FORE!' mahdollisimman lujaa juuri ennen irrotusta (vaikka väylä olisi tyhjä)." },
    { n: "Kivikasvo", d: "Ei minkäänlaista ilmettä tai reaktiota heiton jälkeen. Täysi pokeri." },
    { n: "Jäätyminen", d: "Kohteen on jähmetyttävä täysin paikalleen saattoasentoon 5 sekunniksi heiton jälkeen." },
    { n: "Heikko grip", d: "Kiekosta saa pitää kiinni vain peukalolla ja etusormella." },
    { n: "Hengityskielto", d: "Vedä keuhkot täyteen ilmaa ja pidätä hengitystä koko vauhdinoton ja heiton ajan." },
    { n: "Taikasauva", d: "Osoita koria kiekolla kuin taikasauvalla ennen asettumista heittoon." },
    { n: "Kantapäät irti", d: "Koko heittosuoritus on tehtävä pelkillä päkiöillä seisten." },
    { n: "Pudotus", d: "Kohde joutuu tiputtamaan kiekkonsa maahan ja nostamaan sen juuri ennen heittoa." },
    { n: "Väärä jalka", d: "Tukijalkana on käytettävä väärää jalkaa (oikeakätisellä oikea jalka edessä)." },
    { n: "Ei sormea", d: "Etusormi ei saa koskea kiekon rimiin (reunaan) lainkaan." },
    { n: "Pyyntö", d: "Kohteen on kysyttävä sinulta kohteliaasti lupa heittää ennen suoritusta." },
    { n: "Käänteinen vauhti", d: "Ota vauhtiaskeleet takaperin kävellen." },
    { n: "Kurotus", d: "Heitä mahdollisimman epämukavasta asennosta kurottaen sivuun." },
    { n: "Täysi hiljaisuus", d: "Et saa puhua sanaakaan väylän loppuun asti. Jokaisesta sanasta +1 rangaistus." },
    { n: "Bägi etupuolella", d: "Bägi on pidettävä roikkumassa vatsan puolella heiton ajan." },
    { n: "Haaraseisonta", d: "Jalat on pidettävä leveässä haara-asennossa, ei vauhtiaskeleita." },
    { n: "Kiekon pyöritys", d: "Pyöritä kiekkoa sormenpäällä vähintään kerran ennen heittoa." },
    { n: "Rysty-grippi kämmenellä", d: "Heitä fore, mutta pidä kiinni rystygripillä (Power Grip)." },
    { n: "Huuto", d: "Karjaise apinan lailla juuri kiekon irrotessa kädestä." },
    { n: "Kipeä selkä", d: "Heitä kuin olisit 90-vuotias ja selkä olisi jumissa." },
    { n: "Silmät ristiin", d: "Laita silmät kieroon juuri ennen kuin tähtäät." },
    { n: "Kiitos puille", d: "Jos osut puuhun, sinun on käytävä halaamassa sitä ja kiitettävä." },
    { n: "Varjotikari", d: "Tee 'ninjaliike' vapaalla kädellä samalla kun heität." },
    { n: "Maakosketus", d: "Vapaan käden on koskettava maata heiton saaton aikana." },
    { n: "Golf-asento", d: "Heitä lähestyminen kuten löisit pallogolfia." }
];
minorBases.forEach((base, i) => window.allCards.push({ id: "minor_" + i, n: base.n, d: base.d, tier: "normal", type: "minor_sabotage" }));

// ==========================================
// TASO 2: ISOT SABOTAASIT (Muuttavat fysiikkaa, Max 1 per väylä)
// diff 1 = Helppo (3 P), diff 2 = Vaikea (5 P), diff 3 = Erittäin vaikea (8 P)
// ==========================================
const majorBases = [
    { n: "Kämmenpakko", d: "Heitä seuraava heittosi pakollisella kämmenellä (forehand).", diff: 1 },
    { n: "Rystypakko", d: "Heitä seuraava heittosi pakollisella rystyllä (backhand).", diff: 1 },
    { n: "Pystyheitto", d: "Seuraava heitto on suoritettava pystyheitolla (Upsi/Tomahawk/Thumber).", diff: 2 },
    { n: "Rolleripakko", d: "Kiekon on osuttava maahan kovaa ja rullattava eteenpäin vähintään 10m.", diff: 3 },
    { n: "Putteridraivi", d: "Seuraava avaus tai pitkä heitto on pakko suorittaa putterilla.", diff: 1 },
    { n: "Väärä käsi", d: "Seuraava heitto on heitettävä täysin väärällä/heikommalla kädellä.", diff: 3 },
    { n: "Kiekon Pakkovalinta", d: "Valitse kohteen bägistä 3 kiekkoa, joista hänen on pakko valita heittokiekko.", diff: 1 },
    { n: "Lainakiekko", d: "Anna kohteelle oma kiekkosi. Hänen on pakko heittää seuraava heittonsa sillä.", diff: 1 },
    { n: "Laser-linja", d: "Kiekon on pysyttävä koko lennon ajan alle 2 metrin korkeudella maasta.", diff: 2 },
    { n: "Korkea Hysse", d: "Heitä seuraava heitto jyrkkänä ja poikkeuksellisen korkeana hyzerinä.", diff: 2 },
    { n: "Antsapoliisi", d: "Kiekon on lähdettävä kädestä selkeässä ja jyrkässä anhyzer-kulmassa.", diff: 2 },
    { n: "Scooberi", d: "Suorita lähestymisheitto ylösalaisella scuuberi-tyylillä.", diff: 3 },
    { n: "Turbo-Putt", d: "Seuraava heitto tai putti on suoritettava sormilla kiekon alta työntäen (Turbo).", diff: 2 },
    { n: "Grenade", d: "Kiekko on pidettävä kädessä ylösalaisin peukalo urassa ja heitettävä rystyllä pystysuoraan ylös.", diff: 3 },
    { n: "Vain yksi kiekko", d: "Kohde joutuu pelaamaan tämän väylän loppuun pelkästään yhdellä valitsemallasi kiekolla.", diff: 2 },
    { n: "Sokkoavaus", d: "Avausheitto tiiltä silmät sidottuina (tai tiukasti kiinni). Turvamies ohjeistaa suunnan!", diff: 3 },
    { n: "Kämmen-Roller", d: "Heitto on suoritettava fore-rollerina.", diff: 3 },
    { n: "Midari-Putti", d: "Kaikki putit tällä väylällä on pakko suorittaa midrange-kiekolla.", diff: 1 },
    { n: "Ei draivereita", d: "Kohde ei saa käyttää väylällä nopeampia kiekkoja kuin nopeusluokka 5.", diff: 1 },
    { n: "Draiveriputti", d: "Seuraava putti on suoritettava nopeimmalla pituusdraiverilla mitä bägistä löytyy.", diff: 1 },
    { n: "Istualtaan", d: "Seuraava heitto on pakko heittää maassa istuen (pylly maassa).", diff: 3 },
    { n: "Peilikuva", d: "Kohteen on matkittava edellisen pelaajan heittotyyliä (kämmen/rysty) tismalleen.", diff: 2 },
    { n: "Pakkolayup", d: "Kohde ei saa yrittää koriauraa seuraavalla heitollaan, vaan kiekon on tultava alas väh. 5m päähän korista.", diff: 1 },
    { n: "Mini-kiekko", d: "Jos kohteella on markkeri, hänen on suoritettava seuraava heitto sillä.", diff: 3 },
    { n: "Pizza-grippi", d: "Kiekosta pidetään kiinni molemmin käsin kiinni reunoista (kuin pitsalaatikosta) ja heitetään alakautta.", diff: 3 },
    { n: "Spontaani", d: "Kohteen on heitettävä 3 sekunnin kuluessa siitä, kun vuoro siirtyy hänelle.", diff: 1 },
    { n: "Pakkohysse", d: "Jos kiekko kääntää yli (turn), heitto katsotaan epäonnistuneeksi (+1 rangaistus).", diff: 2 },
    { n: "Polvistumisputti", d: "Kaikki putit tällä väylällä heitetään molemmat polvet maassa.", diff: 2 },
    { n: "Maksimiteho", d: "Seuraava heitto on heitettävä aivan 100% täysillä, vaikka kori olisi 20m päässä.", diff: 3 },
    { n: "Täyskäsi", d: "Kohde joutuu pitämään toisessa kädessä kolmea kiekkoa heittonsa ajan.", diff: 1 },
    { n: "Suora selkä", d: "Selkä on pidettävä täysin suorana koko heiton ajan. Ei saa nojata eteen tai taakse.", diff: 2 },
    { n: "Hyssekulmassa putti", d: "Putti on heitettävä voimakkaassa hyzer-kulmassa koria kohti.", diff: 2 },
    { n: "Kiekkotorni", d: "Aseta kiekon päälle toinen kiekko. Heitä alimmaista niin että ylin vain putoaa maahan.", diff: 3 },
    { n: "Silmät kiinni putti", d: "Kaikki alle 10 metrin putit on vedettävä silmät visusti kiinni.", diff: 3 },
    { n: "Lepokäsi taskuun", d: "Vapaa käsi on pidettävä tiukasti housuntaskussa koko heiton ajan.", diff: 1 },
    { n: "Kenkä pois", d: "Kohteen on otettava heittokäden puoleinen kenkä pois jalasta heiton ajaksi.", diff: 1 },
    { n: "Bägi eteen", d: "Aseta kohteen bägi tasan 1.5 metrin päähän eteen. Heiton on mentävä sen yli tai ohi osumatta.", diff: 2 },
    { n: "Vaakamando", d: "Heiton on pakko lentää jonkin puun oksan ali. Jos oksaa ei ole, alin mahdollinen linja.", diff: 2 },
    { n: "Pitkä odotus", d: "Kun asento on valmis, kohteen on odotettava täysin liikkumatta 10 sekuntia ennen vetoa.", diff: 1 },
    { n: "Painava kiekko", d: "Kohteen on valittava bägistään painavin kiekkonsa seuraavaan heittoon.", diff: 1 },
    { n: "Kevyt kiekko", d: "Kohteen on valittava bägistään kevyin tai alivakain kiekkonsa ja heitettävä sillä.", diff: 1 },
    { n: "Ei saksia", d: "Ristiaskeleet (x-step) ovat kiellettyjä.", diff: 2 },
    { n: "Vastakierre", d: "Kiekon on lähdettävä kädestä siten, että se pyörii ns. väärään suuntaan (esim. rysty ilman rannetta).", diff: 3 },
    { n: "Käännöspakko", d: "Heiton on pakko kaartaa alkuperäisestä heittosuunnasta selkeästi sivuun (turn/fade).", diff: 1 },
    { n: "Aliheitto", d: "Heitto on suoritettava ns. roikkuvana alakauttaheilautuksena.", diff: 3 },
    { n: "Pitkä saatto", d: "Heittokäden on osoitettava koria kohti vähintään 3 sekuntia kiekon irtoamisen jälkeen.", diff: 1 },
    { n: "Pakkopudotus", d: "Jos väylällä on OB, pelaajan on pakko tähdätä vaarallisesti sen lähettyville.", diff: 2 },
    { n: "Rysty-Roller", d: "Heiton on pakko olla rysty-roller.", diff: 3 },
    { n: "Silmät sidottu putti", d: "Paita käärittynä silmien eteen suoritettu putti.", diff: 3 }
];
majorBases.forEach((base, i) => {
    let diffStars = "⭐".repeat(base.diff);
    window.allCards.push({ id: "major_" + i, n: base.n, d: `[Vaikeus: ${diffStars}] ${base.d}`, tier: "normal", type: "major_sabotage", diff: base.diff });
});

// ==========================================
// TASO 1: PERUS HELPOTUKSET (Buffit, Ei pelirajoitusta)
// mech-tägeillä automatisoidaan piste-efektejä (double_win = x2 voitto, etc)
// ==========================================
const buffBases = [
    { n: "Mulligan", d: "Voit uusia oman epäonnistuneen heittosi." },
    { n: "Mulligan (Putti)", d: "Voit uusia epäonnistuneen putin (alle 10m)." },
    { n: "Mulligan (Avaus)", d: "Voit uusia epäonnistuneen avausheiton tiiltä." },
    { n: "Siirto +1m", d: "Voit siirtää kiekkoasi metrin mihin tahansa suuntaan (myös lähemmäs koria)." },
    { n: "Siirto +3m", d: "Voit siirtää kiekkoasi 3 metriä mihin tahansa suuntaan (ei lähemmäs koria)." },
    { n: "Siirto +5m", d: "Voit siirtää kiekkoasi 5 metriä mihin tahansa suuntaan (ei lähemmäs koria)." },
    { n: "Kumous", d: "Peruuta sinuun juuri kohdistettu 1-tason (pieni) sabotaasi." },
    { n: "Vahva Kumous", d: "Peruuta sinuun kohdistettu 2-tason (iso) sabotaasi." },
    { n: "Peilaus", d: "Jos joku pelaa sinuun sabotaasin, voit kääntää sen välittömästi takaisin häneen itseensä." },
    { n: "Puskasta pois", d: "Saat siirtää kiekkosi vapaasti pelattavalle väylälle samalle etäisyydelle korista." },
    { n: "Varaslähtö", d: "Saat heittää 2 avausheittoa tiiltä ja jatkaa niistä vapaasti paremmalla." },
    { n: "Mando-ohitus", d: "Jos väylällä on mando, saat jättää sen huomioimatta ilman rangaistusta." },
    { n: "OB-pelastus", d: "Jos heitit Out of Bounds (OB), saat jatkaa heittopaikalta ilman rangaistusheittoa." },
    { n: "Oksan poisto", d: "Kuvitteellinen oksasaha: Saat jättää huomioimatta yhden edessä olevan oksan tai pensaan (siirrä kiekkoa hieman sivuun)." },
    { n: "Turvamies", d: "Suojaa sinut kaikilta sabotaaseilta koko tämän väylän ajan. Pelattava ennen avausheittoa." },
    { n: "Lähinnä koria", d: "Jos olet lähimpänä koria avauksen jälkeen, saat +1 pelirahaa kassaan." },
    { n: "Kauimpana korista", d: "Jos olet kauimpana korista avauksen jälkeen, saat yhden ilmaisen mulliganin tälle väylälle." },
    { n: "Kiekon etsintä", d: "Jos jonkun kiekko hukkuu, sinun ei tarvitse osallistua sen etsimiseen." },
    { n: "Helppo Putti", d: "Voit siirtää kiekkosi C1 (10m) rajalta suoraan 3 metrin päähän korista (+1 heitto lisätään tulokseen silti)." },
    { n: "Tuulen tyven", d: "Kuvitteellinen myötätuuli: Saat vähentää 1 heiton lopputuloksestasi tällä väylällä, jos onnistut saamaan Par-tuloksen tai paremman." },
    { n: "Yhden säännön kumo", d: "Jos väylällä on väyläsääntö, sinun ei tarvitse noudattaa sitä." },
    { n: "Varakiekko", d: "Jos heität kiekkosi veteen tai katoaa, et saa rangaistusheittoa." },
    { n: "Täydellinen asento", d: "Saat ottaa makuuasennon (tai minkä tahansa) ilman jalkavirhettä markkerin takaa." },
    { n: "Tuplavoitto", d: "Jos voitat tämän väylän (yksin tai jaettuna), saat x2 väylävoiton pisteet!", mech: "double_win" },
    { n: "Tuplatehtävä", d: "Jos voitat väylätehtävän, saat siitä tuplamäärän (x2) rahaa automaattisesti.", mech: "double_task" },
    { n: "Korttituho", d: "Tuhoa yksi satunnainen kortti valitsemasi vastustajan kädestä (Ei vie varoja)." },
    { n: "Pankkiiri", d: "Saat ottaa pankista yhden satunnaisen 1-tason (pienen) sabotaasin itsellesi ilmaiseksi." },
    { n: "Tiipaikan vaihto", d: "Saat heittää avauksesi mistä tahansa kohtaa tiipadiltä tai sen sivusta (max 2m säteellä)." },
    { n: "Uusi nosto", d: "Hylkää kaikki kädessäsi olevat kortit ja nosta pakasta 3 uutta." },
    { n: "Taikamarkkeri", d: "Saat asettaa markkerisi kiekon ETEEN (15cm lähemmäs koria)." },
    { n: "Kilpi", d: "Aktivoituu heti kun se pelataan. Seuraava sinuun kohdistuva sabotaasi mitätöityy automaattisesti." },
    { n: "Pitkä heitto", d: "Jos heität yli 100m, saat nostaa palkinnoksi uuden kortin." },
    { n: "Kiekon lainaus", d: "Voit ottaa yhden vastustajan kiekon omaan käyttöösi tälle väylälle." },
    { n: "Ketjuralli", d: "Jos putti osuu ketjuihin mutta sylkee ulos, se lasketaan menneeksi." },
    { n: "Paluukortti", d: "Hae poistopakasta/käytetyistä yksi haluamasi normaali-tason kortti takaisin käteesi." },
    { n: "Caddien tuki", d: "Määrää yksi pelaaja toimimaan sinun 'caddienä'. Hänen on kannettava bägiäsi seuraavalle väylälle." },
    { n: "Riskitön", d: "Jos heität seuraavan heittosi vesiesteeseen tai saavuttamattomiin, saat heittää sen rangaistuksetta uudelleen tiiltä/edellisestä paikasta." },
    { n: "Kymppimetrinen", d: "Saat mitata 10m ringin askelilla sen sijaan, että joku muu arvioisi sen." },
    { n: "Ei sääntöjä", d: "Voit astua markkerin yli heti irrotuksen jälkeen, vaikka olisit alle 10m sisällä." },
    { n: "Parantaja", d: "Poista valitsemaltasi pelaajalta yksi rangaistusheitto tuloskortista (voi käyttää myös itseensä)." },
    { n: "Valinnanvapaus", d: "Määrää toinen pelaaja ottamaan vastaan hänelle pelattu sabotaasi, ja tee itse se mikä hänelle oli määrätty (vaihdatte sabotaaseja)." },
    { n: "Puttiapu", d: "Saat heittää 2 kiekkoa putissa, ja valita kumpaa käytät tuloksena." },
    { n: "Katsomon tuki", d: "Muiden pelaajien on taputettava sinulle suorituksen jälkeen, riippumatta siitä miten se meni." },
    { n: "Korttisade", d: "Nosta 2 uutta korttia pakasta." },
    { n: "Askel-etumatka", d: "Saat ottaa yhden normaalin pituisen askeleen lähemmäs koria ennen avausheittoa." },
    { n: "Suunta on oikea", d: "Jos heitto lähtee täysin väärään suuntaan (yli 45 astetta tavoitteesta), saat uusia sen." },
    { n: "Ketjuklinikka", d: "Jos osut rautoihin (ala/ylä) mutta ei ketjuihin, saat uusia putin." },
    { n: "Kiekkotietäjä", d: "Kysy neuvoa keltä tahansa vastustajalta. Hänen on pakko antaa paras mahdollinen vinkkinsä kiekon ja linjan valintaan." },
    { n: "Helpotettu väylä", d: "Jos väylällä on OB, koko väylä pelataan ilman OB-sääntöjä (kiekko pelataan sieltä minne jää, ei rangaistusta)." }
];
buffBases.forEach((base, i) => window.allCards.push({ id: "buff_" + i, n: base.n, d: base.d, tier: "normal", type: "buff", mech: base.mech || null }));

// ==========================================
// TASO 3: KAUPAN MONSTERIKORTIT (Premium)
// Huom: Rich get richer -ilmiö poistettu. Ei voi varastaa saldoa suoraan. 
// aoe: true tagilla kortti valitsee automaattisesti kaikki vastustajat
// ==========================================
const monsterBases = [
    { n: "Köyhyyskirous", d: "Kohde ei saa ollenkaan passiivista tuloa tältä väylältä.", type: "major_sabotage", price: 12, mech: "deny_passive" },
    { n: "Veromätky", d: "KAIKKI vastustajat menettävät passiivisen tulonsa tältä väylältä.", type: "major_sabotage", price: 20, aoe: true, mech: "deny_passive" },
    { n: "Palkkion eväys", d: "Kohde ei saa väylävoiton pisteitä, vaikka hän voittaisi tämän väylän.", type: "major_sabotage", price: 15, mech: "deny_win" },
    { n: "Täystuho", d: "Määrää yksi Iso Sabotaasi (Taso 2) täysin itse keksimilläsi säännöillä kohteelle.", type: "major_sabotage", price: 20 },
    { n: "OB-Magneetti", d: "Valitse kohde. Jos hän menee OB:lle tällä väylällä, hän saa +2 rangaistusheittoa normaalin +1 sijaan.", type: "major_sabotage", price: 18 },
    { n: "Pankin Tuki", d: "Saat pankista välittömästi uuden rahoituksen (+8 P).", type: "buff", price: 12 }, // HUOM! Tämä on buffi joka antaa 8P ja maksaa 12P, vähän kuin säästöpossu.
    { n: "Kiekkolukko", d: "Kiellä kohdetta käyttämästä hänen luottodraiveriaan koko loppukierroksen ajan.", type: "major_sabotage", price: 25 },
    { n: "Laser-Tähtäin", d: "Voit siirtää mitä tahansa alle 20m puttiasi 5 metriä lähemmäs koria.", type: "buff", price: 15 },
    { n: "Vaihtokauppa", d: "Vaihda huono avausheittosi paikkaa kohteen hyvän avauksen kanssa.", type: "major_sabotage", price: 25 },
    { n: "Jumal-Kumous", d: "Pelaa tämä peruuttaaksesi MIKÄ TAHANSA sabotaasi (myös monsteri).", type: "buff", price: 18 },
    { n: "Par-Varmistus", d: "Heitä normaalisti. Tuloskorttiisi merkitään automaattisesti enintään PAR (Vaikka heittäisit 10).", type: "buff", price: 22, mech: "force_par" },
    { n: "Korttijäädytys", d: "Kohde ei saa pelata yhtäkään korttia kädestään seuraavien 3 väylän aikana.", type: "major_sabotage", price: 20 },
    { n: "Ukkosmyrsky", d: "KAIKKI vastustajat heittävät avauksensa väärällä kädellä tällä väylällä.", type: "major_sabotage", price: 30, aoe: true },
    { n: "Haamukiekko", d: "Koko loppukierroksen ajan, kerran väylässä saat peruuttaa yhden heittosi ilmaiseksi.", type: "buff", price: 35 },
    { n: "Korttikato", d: "Kohde ei saa nostaa uusia kortteja tämän väylän tulosten jaon yhteydessä, vaikka hän häviäisi.", type: "major_sabotage", price: 18, mech: "deny_draw" },
    { n: "Magneettikori", d: "Seuraava putti alle 15m lasketaan aina sisään menneeksi, osuipahan se tai ei.", type: "buff", price: 20 }
];
monsterBases.forEach((base, i) => window.allCards.push({ id: "monster_" + i, n: `${base.n}`, d: base.d, tier: "premium", type: base.type, price: base.price, aoe: base.aoe || false, mech: base.mech || null }));

// ==========================================
// VÄYLÄSÄÄNNÖT (Koko porukan tehtävät & säännöt)
// ==========================================
window.holeRules = [
    { type: "bounty", n: "CTP-Kisa", d: "Tiiltä lähimmäksi korijalkaa osunut avaus voittaa väylätehtävän." },
    { type: "bounty", n: "Pitkä Putti", d: "Väylän pisimmän onnistuneen putin tekijä voittaa väylätehtävän." },
    { type: "rule", n: "Putteri-Ruletti", d: "Koko väylä pelataan pelkillä puttereilla. Muut kiekot kielletty." },
    { type: "bounty", n: "Pelastaja", d: "Ensimmäinen pelaaja, joka menee ryteikköön tai OB:lle, mutta pelastaa silti Par-tuloksen, voittaa tehtävän." },
    { type: "rule", n: "Seisova Avaus", d: "Kukaan ei saa ottaa yhtään vauhtiaskelta avausheitossaan tiiltä." },
    { type: "rule", n: "Kämmenväylä", d: "Kaikki yli 10 metrin lähestymiset ja avaukset on pakko heittää kämmeneltä (forehand)." },
    { type: "rule", n: "Hiljaisuus", d: "Koko väylä pelataan täydessä hiljaisuudessa. Jokaisesta sanasta +1 rangaistusheitto." },
    { type: "rule", n: "Speed Golf", d: "Tätä väylää ei mietitä. Jokaisella on 5 sekuntia aikaa heittää omalla vuorollaan." },
    { type: "bounty", n: "Puu-Kuningas", d: "Se pelaaja, joka osuu eniten puihin tällä väylällä mutta EI saa eniten heittoja, voittaa tehtävän." },
    { type: "rule", n: "Upsi-Avaus", d: "Kaikkien pelaajien on pakko avata tiiltä pystyheitolla (Upsi tai Thumber)." },
    { type: "bounty", n: "Ensimmäinen rauta", d: "Ensimmäinen pelaaja joka puttaa alarautaan tai ylärautaan (ei sisään), voittaa tehtävän." },
    { type: "rule", n: "Rystyn kielto", d: "Rystyheitot ovat täysin kiellettyjä tällä väylällä." },
    { type: "bounty", n: "Parkkeeraus", d: "Se pelaaja, jonka lähestymisheitto (tai avaus) jää alle 2 metrin päähän korista, voittaa tehtävän." },
    { type: "rule", n: "Väärä käsi avaus", d: "Kaikkien on suoritettava avausheitto heikommalla kädellään." },
    { type: "rule", n: "Kääntöjärjestys", d: "Heittojärjestys on täysin päinvastainen. Huonoiten edellisellä väylällä pelannut avaa ensin." },
    { type: "bounty", n: "Ei sirkkeliä", d: "Pelaaja, joka selviää koko väylän osumatta kertaakaan puuhun, voittaa tehtävän." },
    { type: "rule", n: "Bägi selässä", d: "Kaikki pelaavat koko väylän bägi tai reppu tiukasti selässä." },
    { type: "rule", n: "Yhden kiekon taktiikka", d: "Jokaisen on valittava vain YKSI kiekko, jolla pelataan väylä alusta loppuun." },
    { type: "bounty", n: "Bullseye Putti", d: "Ensimmäinen, joka upottaa putin yli 10 metrin (C1) rajalta, voittaa tehtävän." },
    { type: "rule", n: "Rolleriavaus", d: "Kaikkien on pakko yrittää roller-avausta tiiltä." },
    { type: "bounty", n: "Nosto", d: "Se pelaaja, jolla on lyhyin putti ('nosto') jäljellä heittojen jälkeen, voittaa tehtävän." },
    { type: "rule", n: "Vasen laita", d: "Kaikki avaukset on pyrittävä heittämään väylän vasenta laitaa pitkin (hyzer-reitti)." },
    { type: "rule", n: "Kehu kaveria", d: "Jokaisen on kehuttava vilpittömästi jotain toista pelaajaa oman heittonsa jälkeen." },
    { type: "bounty", n: "OB-Sukellus", d: "Ensimmäinen joka heittää kiekkonsa OB:lle (tai pahimpaan metsään), 'voittaa' lohdutustehtävän rahoituksen." },
    { type: "rule", n: "Ei hyppyputteja", d: "Kaikki hyppy- tai steppiputit on kielletty tällä väylällä, vaikka oltaisiin ringin ulkopuolella." },
    { type: "rule", n: "Kiekkoswap", d: "Jokainen ojentaa koko bäginsä seuraavalle pelaajalle oikealle tällä väylällä." },
    { type: "bounty", n: "Birdie-jahti", d: "Kaikki ketkä tekevät tällä väylällä Birdien (alle parin), voittavat tehtävän." },
    { type: "rule", n: "Kyykkyputti", d: "Kaikki C1 (10m) sisällä olevat putit on heitettävä syvästä kyykystä." },
    { type: "rule", n: "Huutokisat", d: "Aina kun kiekko irtoaa, heittäjän on pakko huutaa jotain kovaan ääneen." },
    { type: "bounty", n: "Midarikuningas", d: "Pelaaja, joka pääsee Mid-range -kiekolla lähimmäksi koria avauksellaan, voittaa tehtävän." },
    { type: "rule", n: "Ajanotto", d: "Koko ryhmän on pelattava tämä väylä alusta loppuun alle 3 minuutissa. Jos ei ehdi, kaikki saavat +1 tulokseen." },
    { type: "rule", n: "Aina markkeri", d: "Joka ikinen heitto (myös tap-in) on merkattava markkerilla ennen heittoa." },
    { type: "bounty", n: "Bogey-Vapaa", d: "Kaikki jotka pelaavat väylän ilman Bogeya (yli par), jakavat tehtävän voiton." },
    { type: "rule", n: "Midari-Only", d: "Väylä on pakko pelata vain ja ainoastaan midareilla." },
    { type: "rule", n: "Silmät kiinni putti", d: "Kaikki alle 5 metrin putit on vedettävä silmät visusti kiinni." },
    { type: "bounty", n: "Nopein heittäjä", d: "Se pelaaja, joka pelaa oman vuoronsa poikkeuksetta nopeimmin (ilman viivyttelyä), voittaa tehtävän." },
    { type: "rule", n: "Pakkohysse", d: "Jokaisen heiton on pakko kaartaa alkuperäiseen kaarresuuntaansa. Jos kääntää yli, huuto: 'Väärä!'." },
    { type: "bounty", n: "Kiekon etsijä", d: "Se, joka ensimmäisenä löytää toisen pelaajan kadonneen kiekon, voittaa tehtävän." },
    { type: "rule", n: "Haaraseisonta", d: "Kaikki avausheitot on heitettävä paikaltaan haaraseisonnasta." },
    { type: "rule", n: "Tuplaputit", d: "Jos missaat ensimmäisen putin (alle 10m), joudut hakemaan kiekon ja yrittämään samasta paikasta kunnes menee. Jokainen yritys maksaa +1 heiton." },
    { type: "bounty", n: "Sweet Spot", d: "Kuka pääsee avauksella parhaaseen 'sweet spottiin' (pelattavimpaan paikkaan), voittaa tehtävän." },
    { type: "rule", n: "Golf-taputukset", d: "Muiden pelaajien on annettava hienostuneet ja hiljaiset sormenpää-taputukset jokaisen hyvän heiton jälkeen." },
    { type: "rule", n: "Väärä liikerata", d: "Kaikki vauhdinotto tapahtuu peruuttaen tiille päin." },
    { type: "bounty", n: "Kierrekone", d: "Kenellä kiekko skippaa/pomppaa pisimmälle maahanosumisen jälkeen, voittaa tehtävän." },
    { type: "rule", n: "Vain sivuittain", d: "Vauhtiaskeleet saa ottaa vain suoraan sivuttain (ristiaskel ilman eteenpäinmenoa)." },
    { type: "rule", n: "Ketjuviha", d: "Kiekko on pakko upottaa suoraan koriaan pehmeästi. Jos heität niin kovaa, että rämähtää ikävästi, +1 rangaistus." },
    { type: "bounty", n: "Korijalan halaaja", d: "Kenen kiekko nojaa lähimpänä tolppaan, voittaa tehtävän." },
    { type: "rule", n: "Fore-putti", d: "Kaikki putit on suoritettava forella (kämmenheitto)." },
    { type: "bounty", n: "Riskinottaja", d: "Se, joka yrittää rohkeinta ja vaikeinta linjaa (onnistui tai ei), voittaa tehtävän (ryhmä äänestää)." },
    { type: "rule", n: "Normaali Väylä", d: "Tällä väylällä ei ole erikoissääntöjä. Pelkkää puhdasta frisbeegolfia." }
];
